package:
   name: heacore
   version: "0.1.1"

source:
   git_url: https://github.com/Areustle/fermi-heacore.git

build:
  number: 0

requirements:
  build:
    - readline <=6.2-0
    - cfitsio
  run:
    - readline <=6.2-0
    - cfitsio
